/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ponyseba.finiquitoscalc.view;

import com.ponyseba.finiquitoscalc.controller.SesionController;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.SesionUsuario;

/**
 *
 * @author jgval
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form Form_Login
     */
    public FormLogin() {
        initComponents();
        this.setTitle("Sistema de cálculo de finiquitos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_emailUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_passwordUsuario = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jbtn_irCrearCuenta = new javax.swing.JButton();
        jBtn_ingresarSesion = new javax.swing.JButton();
        jLabel_errorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Rubik", 1, 24)); // NOI18N
        jLabel1.setText("Ingrese a su cuenta");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Email");

        jLabel_emailUsuario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_emailUsuario.setActionCommand("<Not Set>");
        jLabel_emailUsuario.setBorder(null);
        jLabel_emailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel_emailUsuarioActionPerformed(evt);
            }
        });
        jLabel_emailUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel_emailUsuarioKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Contraseña");

        jLabel_passwordUsuario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_passwordUsuario.setBorder(null);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("¿No tienes cuenta? ");

        jbtn_irCrearCuenta.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jbtn_irCrearCuenta.setForeground(new java.awt.Color(51, 153, 255));
        jbtn_irCrearCuenta.setText("Crear una cuenta");
        jbtn_irCrearCuenta.setBorder(null);
        jbtn_irCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_irCrearCuentaActionPerformed(evt);
            }
        });

        jBtn_ingresarSesion.setBackground(new java.awt.Color(204, 204, 204));
        jBtn_ingresarSesion.setText("Ingresar");
        jBtn_ingresarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ingresarSesionActionPerformed(evt);
            }
        });

        jLabel_errorMessage.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jLabel_errorMessage.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_errorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_errorMessage.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2)
                            .addComponent(jLabel_emailUsuario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn_irCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(jLabel_errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_passwordUsuario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(464, 464, 464)
                        .addComponent(jBtn_ingresarSesion)))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_emailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_passwordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel_errorMessage)
                .addGap(26, 26, 26)
                .addComponent(jBtn_ingresarSesion)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jbtn_irCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_emailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel_emailUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_emailUsuarioActionPerformed

    private void jbtn_irCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_irCrearCuentaActionPerformed
        FormCrearCuenta fcc = new FormCrearCuenta();
        fcc.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_irCrearCuentaActionPerformed

    private void jBtn_ingresarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ingresarSesionActionPerformed
        // TODO add your handling code here:
        
        boolean loginValido = false;
        String emailUsuario = this.jLabel_emailUsuario.getText();
        char[] passwordUsuario = this.jLabel_passwordUsuario.getPassword();
        SesionUsuario sesionUsuario = new SesionUsuario();
        
        FormPanelCentral formFormularioFiniquito = new FormPanelCentral();
        SesionController sesionController = new SesionController();
       
        Pattern regexPattern = Pattern.compile("\\b[\\w\\.-]+@[\\w\\.-]+\\.\\w{2,4}\\b");
        
        if(!regexPattern.matcher(emailUsuario).matches()){
            this.jLabel_errorMessage.setText("formato email inválido, ejemplo: usuario@mail.com");
        } else {
            this.jLabel_errorMessage.setText("");
            if(emailUsuario.trim().length() > 0 && passwordUsuario.length > 0){
            SesionUsuario usuarioValidar = sesionController.validarUsuario(emailUsuario, passwordUsuario);
            sesionUsuario.setSesionValida(usuarioValidar.isSesionValida());
            sesionUsuario.setMensajeError(usuarioValidar.getMensajeError());
            sesionUsuario.setUsuarioLogueado(usuarioValidar.getUsuarioLogueado());
            System.out.println(sesionUsuario.toString());
            
            if(sesionUsuario.getMensajeError().trim().length() > 0){
                this.jLabel_errorMessage.setText(sesionUsuario.getMensajeError());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Datos incorrectos!");
        }
        
        if(sesionUsuario.isSesionValida()) {
            formFormularioFiniquito.setVisible(true);
            formFormularioFiniquito.setAlwaysOnTop(true);
            this.setVisible(false);
        }
            
        }
        
        
        
        
        
    }//GEN-LAST:event_jBtn_ingresarSesionActionPerformed

    private void jLabel_emailUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel_emailUsuarioKeyTyped
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jLabel_emailUsuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_ingresarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jLabel_emailUsuario;
    private javax.swing.JLabel jLabel_errorMessage;
    private javax.swing.JPasswordField jLabel_passwordUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtn_irCrearCuenta;
    // End of variables declaration//GEN-END:variables
}
