/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ponyseba.finiquitoscalc.view;

import com.ponyseba.finiquitoscalc.controller.FiniquitoCalcController;
import com.ponyseba.finiquitoscalc.controller.FormularioFiniquitoController;
import com.ponyseba.finiquitoscalc.utils.ConstantesCausales;
import com.ponyseba.finiquitoscalc.utils.Utils;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import model.DatosEntradaMes;
import model.Finiquito;
import model.FormularioFiniquito;
import model.SesionUsuario;

/**
 *
 * @author sebastiankravetz
 */
public class FormFormularioSueldoVariable extends javax.swing.JFrame {
    
    SesionUsuario sesionUsuario;
    
    HashMap<String, String> listaCausales = ConstantesCausales.causalesHashMap();
    
    public void llenarComboBox() {
        for(Map.Entry causal : listaCausales.entrySet()) {
            this.jComboBox_causalesLista.addItem((String) causal.getValue());
        }
    }
    
    
    /**
     * Creates new form FormFormularioFiniquito
     */
    public FormFormularioSueldoVariable(SesionUsuario sesionUsuario) {
        initComponents();
        llenarComboBox();
        this.jComboBox_causalesLista.setSelectedItem(ConstantesCausales.PLACEHOLDER_VALUE);
        this.sesionUsuario = sesionUsuario;
        System.out.println(sesionUsuario);
    }

    public FormFormularioSueldoVariable() {
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        datePicker_fechaIngresoFijo = new com.github.lgooddatepicker.components.DatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datePicker_fechaEgresoFijo = new com.github.lgooddatepicker.components.DatePicker();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_causalesLista = new javax.swing.JComboBox<>();
        jCheckBox_zonaExtremaFijo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jTextField_sueldoBaseVariableM1 = new javax.swing.JTextField();
        jTextField_gratificacionVariableM1 = new javax.swing.JTextField();
        jTextField_bonoImponibleVariableM1 = new javax.swing.JTextField();
        jTextField_colacionVariableM1 = new javax.swing.JTextField();
        jTextField_movilizacionVariableM3 = new javax.swing.JTextField();
        jTextField_chequeRestaurantVariableM1 = new javax.swing.JTextField();
        jTextField_desgasteHerramientasM1 = new javax.swing.JTextField();
        jTextField_viaticosVariablesM1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_sueldoBaseVariableM2 = new javax.swing.JTextField();
        jTextField_sueldoBaseVariableM3 = new javax.swing.JTextField();
        jTextField_colacionVariableM2 = new javax.swing.JTextField();
        jTextField_colacionVariableM3 = new javax.swing.JTextField();
        jTextField_desgasteHerramientasM3 = new javax.swing.JTextField();
        jTextField_desgasteHerramientasM2 = new javax.swing.JTextField();
        jTextField_gratificacionVariableM3 = new javax.swing.JTextField();
        jTextField_gratificacionVariableM2 = new javax.swing.JTextField();
        jTextField_comisionesVariableM1 = new javax.swing.JTextField();
        jTextField_movilizacionVariableM2 = new javax.swing.JTextField();
        jTextField_viaticosVariablesM3 = new javax.swing.JTextField();
        jTextField_viaticosVariablesM2 = new javax.swing.JTextField();
        jTextField_chequeRestaurantVariableM2 = new javax.swing.JTextField();
        jTextField_chequeRestaurantVariableM3 = new javax.swing.JTextField();
        jTextField_bonoImponibleVariableM3 = new javax.swing.JTextField();
        jTextField_bonoImponibleVariableM2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField_semanaCorridaVariableM2 = new javax.swing.JTextField();
        jTextField_semanaCorridaVariableM3 = new javax.swing.JTextField();
        jTextField_semanaCorridaVariableM1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField_movilizacionVariableM1 = new javax.swing.JTextField();
        jTextField_comisionesVariableM2 = new javax.swing.JTextField();
        jTextField_comisionesVariableM3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_diasVacacionesTomados = new javax.swing.JTextPane();
        jButton_limpiarCamposFiniquitoFijo = new javax.swing.JButton();
        jButton_calcularFiniquitoSalarioFijo1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu_salir = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1010, 790));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora de Finiquitos: Salario Variable");
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fechas"));

        jLabel2.setText("Fecha de Ingreso:");

        jLabel3.setText("Seleccione causal de término:");

        jLabel4.setText("Fecha de Egreso:");

        jLabel5.setText("Zona Extrema:");

        jComboBox_causalesLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_causalesListaActionPerformed(evt);
            }
        });

        jCheckBox_zonaExtremaFijo.setText("Sí");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_zonaExtremaFijo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(datePicker_fechaIngresoFijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datePicker_fechaEgresoFijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_causalesLista, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datePicker_fechaIngresoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datePicker_fechaEgresoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_causalesLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_zonaExtremaFijo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Salario"));

        jTextField_sueldoBaseVariableM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sueldoBaseVariableM1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Sueldo Base(*):");

        jLabel9.setText("Gratificación:");

        jLabel10.setText("Bono Imponible:");

        jLabel11.setText("Colación:");

        jLabel12.setText("Movilización:");

        jLabel13.setText("Cheque Restaurant:");

        jLabel14.setText("<html>Desgaste<br>Herramientas</html>");

        jLabel15.setText("Viáticos");

        jTextField_comisionesVariableM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_comisionesVariableM1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Semana corrida:");

        jTextField_semanaCorridaVariableM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_semanaCorridaVariableM1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Comisiones:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ingresar datos de los últimos 3 meses");
        jLabel6.setFont(new java.awt.Font("Ligconsolata", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_sueldoBaseVariableM2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_sueldoBaseVariableM3)
                        .addComponent(jLabel11)
                        .addComponent(jTextField_colacionVariableM1)
                        .addComponent(jTextField_colacionVariableM2)
                        .addComponent(jTextField_colacionVariableM3)
                        .addComponent(jTextField_sueldoBaseVariableM1))
                    .addComponent(jTextField_desgasteHerramientasM1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_desgasteHerramientasM3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_desgasteHerramientasM2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_movilizacionVariableM3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_gratificacionVariableM3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_gratificacionVariableM2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_movilizacionVariableM2)
                        .addComponent(jTextField_movilizacionVariableM1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_gratificacionVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_sueldoBaseVariableM2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_sueldoBaseVariableM3)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField_colacionVariableM1)
                                    .addComponent(jTextField_colacionVariableM2)
                                    .addComponent(jTextField_colacionVariableM3)
                                    .addComponent(jTextField_sueldoBaseVariableM1))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_movilizacionVariableM3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_gratificacionVariableM3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_gratificacionVariableM2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_movilizacionVariableM2)
                                        .addComponent(jTextField_movilizacionVariableM1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jTextField_gratificacionVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextField_desgasteHerramientasM1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)

                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_bonoImponibleVariableM1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_bonoImponibleVariableM3)
                                .addComponent(jTextField_bonoImponibleVariableM2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jTextField_chequeRestaurantVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_chequeRestaurantVariableM2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_chequeRestaurantVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField_semanaCorridaVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField_desgasteHerramientasM3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_semanaCorridaVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField_desgasteHerramientasM2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_semanaCorridaVariableM2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))))
=======
                            .addComponent(jTextField_viaticosVariablesM1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel15)
                                .addComponent(jTextField_viaticosVariablesM2)
                                .addComponent(jTextField_viaticosVariablesM3)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_comisionesVariableM1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_comisionesVariableM2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_comisionesVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField_bonoImponibleVariableM1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_bonoImponibleVariableM3)
                        .addComponent(jTextField_bonoImponibleVariableM2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_chequeRestaurantVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_chequeRestaurantVariableM2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_chequeRestaurantVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_semanaCorridaVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_semanaCorridaVariableM2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_semanaCorridaVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(121, 121, 121))
>>>>>>> 70b6bd5 ([@wwiiddeeweb] fixes on forms)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_sueldoBaseVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jTextField_sueldoBaseVariableM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_sueldoBaseVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_colacionVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_colacionVariableM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_colacionVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_desgasteHerramientasM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_desgasteHerramientasM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_desgasteHerramientasM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_bonoImponibleVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jTextField_bonoImponibleVariableM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_bonoImponibleVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jTextField_chequeRestaurantVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_chequeRestaurantVariableM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_chequeRestaurantVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_semanaCorridaVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_semanaCorridaVariableM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_semanaCorridaVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_gratificacionVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jTextField_gratificacionVariableM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_gratificacionVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_movilizacionVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_movilizacionVariableM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_movilizacionVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_viaticosVariablesM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_viaticosVariablesM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_viaticosVariablesM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_comisionesVariableM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_comisionesVariableM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_comisionesVariableM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Vacaciones Disfrutadas"));

        jLabel7.setText("Número de días de vacaciones tomados:");

        jScrollPane1.setViewportView(jTextPane_diasVacacionesTomados);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jButton_limpiarCamposFiniquitoFijo.setText("Limpiar todos los campos");
        jButton_limpiarCamposFiniquitoFijo.setBackground(new java.awt.Color(204, 204, 204));
        jButton_limpiarCamposFiniquitoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarCamposFiniquitoFijoActionPerformed(evt);
            }
        });

        jButton_calcularFiniquitoSalarioFijo1.setText("Calcular Finiquito");
        jButton_calcularFiniquitoSalarioFijo1.setBackground(new java.awt.Color(204, 204, 204));
        jButton_calcularFiniquitoSalarioFijo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calcularFiniquitoSalarioFijo1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Menú");

        jMenuItem1.setText("Panel Central");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Calcular Finiquito Salario Fijo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu_salir.setText("Salir");
        jMenu_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_salirMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenu_salirMouseReleased(evt);
            }
        });
        jMenu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_salirActionPerformed(evt);
            }
        });
        jMenu_salir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu_salirKeyPressed(evt);
            }
        });
        jMenuBar1.add(jMenu_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_calcularFiniquitoSalarioFijo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_limpiarCamposFiniquitoFijo, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))))

                        .addGap(18, 18, 18)

                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
=======
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_limpiarCamposFiniquitoFijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_calcularFiniquitoSalarioFijo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
>>>>>>> 70b6bd5 ([@wwiiddeeweb] fixes on forms)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton_limpiarCamposFiniquitoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_calcularFiniquitoSalarioFijo1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_causalesListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_causalesListaActionPerformed
        // TODO add your handling code here:
        String itemName = (String) this.jComboBox_causalesLista.getSelectedItem();
    }//GEN-LAST:event_jComboBox_causalesListaActionPerformed

    private void jButton_limpiarCamposFiniquitoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarCamposFiniquitoFijoActionPerformed
        // TODO add your handling code here:
        this.jTextField_sueldoBaseVariableM1.setText("");
        this.jTextField_gratificacionVariableM1.setText("");
        this.jTextField_bonoImponibleVariableM1.setText("");
        this.jTextField_colacionVariableM1.setText("");
        this.jTextField_movilizacionVariableM3.setText("");
        this.jTextField_chequeRestaurantVariableM1.setText("");
        this.jTextField_desgasteHerramientasM1.setText("");
        this.jTextField_viaticosVariablesM1.setText("");
        datePicker_fechaIngresoFijo.clear();
        datePicker_fechaEgresoFijo.clear();
        this.jCheckBox_zonaExtremaFijo.setSelected(false);
        jTextPane_diasVacacionesTomados.setText("");
        this.jComboBox_causalesLista.setSelectedItem(ConstantesCausales.PLACEHOLDER_VALUE);
        
    }//GEN-LAST:event_jButton_limpiarCamposFiniquitoFijoActionPerformed

    private void jButton_calcularFiniquitoSalarioFijo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calcularFiniquitoSalarioFijo1ActionPerformed
        // TODO add your handling code here:
        int montoSueldoFijo = Integer.parseInt(this.jTextField_sueldoBaseVariableM1.getText());
        int montoGratificacion = Integer.parseInt(this.jTextField_gratificacionVariableM1.getText());
        int montoBonoImponible = Integer.parseInt(this.jTextField_bonoImponibleVariableM1.getText());
        int montoColacion = Integer.parseInt(this.jTextField_colacionVariableM1.getText());
        int montoMovilizacion = Integer.parseInt(this.jTextField_movilizacionVariableM1.getText());
        int montoChequeRestaurant = Integer.parseInt(this.jTextField_chequeRestaurantVariableM1.getText());
        int montoDesgasteHerramientas = Integer.parseInt(this.jTextField_desgasteHerramientasM1.getText());
        int montoViaticos = Integer.parseInt(this.jTextField_viaticosVariablesM1.getText());
        int montoComisiones = Integer.parseInt(this.jTextField_comisionesVariableM1.getText());
        int montoSemanaCorrida = Integer.parseInt(this.jTextField_semanaCorridaVariableM1.getText());
        LocalDate fechaIngresoFijo = datePicker_fechaIngresoFijo.getDate();
        LocalDate fechaEgresoFijo = datePicker_fechaEgresoFijo.getDate();
        boolean esZonaExtrema = this.jCheckBox_zonaExtremaFijo.isEnabled();
        Set<String> causalDespido = Utils.getKeysByValue(listaCausales, (String) jComboBox_causalesLista.getSelectedItem());
        String artCausalDespido = (String) causalDespido.toArray()[0];
        
        int diasTomadosVacaciones = Integer.parseInt(jTextPane_diasVacacionesTomados.getText());
        
        DatosEntradaMes mesUno = new DatosEntradaMes(montoSueldoFijo, montoGratificacion, montoColacion, montoMovilizacion, montoBonoImponible, montoChequeRestaurant, montoDesgasteHerramientas, montoViaticos, montoComisiones, montoSemanaCorrida);
        
        int montoSueldoFijo2 = Integer.parseInt(this.jTextField_sueldoBaseVariableM2.getText());
        int montoGratificacion2 = Integer.parseInt(this.jTextField_gratificacionVariableM2.getText());
        int montoBonoImponible2 = Integer.parseInt(this.jTextField_bonoImponibleVariableM2.getText());
        int montoColacion2 = Integer.parseInt(this.jTextField_colacionVariableM2.getText());
        int montoMovilizacion2 = Integer.parseInt(this.jTextField_movilizacionVariableM2.getText());
        int montoChequeRestaurant2 = Integer.parseInt(this.jTextField_chequeRestaurantVariableM2.getText());
        int montoDesgasteHerramientas2 = Integer.parseInt(this.jTextField_desgasteHerramientasM2.getText());
        int montoViaticos2 = Integer.parseInt(this.jTextField_viaticosVariablesM2.getText());
        int montoComisiones2 = Integer.parseInt(this.jTextField_comisionesVariableM2.getText());
        int montoSemanaCorrida2 = Integer.parseInt(this.jTextField_semanaCorridaVariableM2.getText());
        DatosEntradaMes mesDos = new DatosEntradaMes(montoSueldoFijo2, montoGratificacion2, montoColacion2, montoMovilizacion2, montoBonoImponible2, montoChequeRestaurant2, montoDesgasteHerramientas2, montoViaticos2, montoComisiones2, montoSemanaCorrida2);
        
        int montoSueldoFijo3 = Integer.parseInt(this.jTextField_sueldoBaseVariableM3.getText());
        int montoGratificacion3 = Integer.parseInt(this.jTextField_gratificacionVariableM3.getText());
        int montoBonoImponible3 = Integer.parseInt(this.jTextField_bonoImponibleVariableM3.getText());
        int montoColacion3 = Integer.parseInt(this.jTextField_colacionVariableM3.getText());
        int montoMovilizacion3 = Integer.parseInt(this.jTextField_movilizacionVariableM3.getText());
        int montoChequeRestaurant3 = Integer.parseInt(this.jTextField_chequeRestaurantVariableM3.getText());
        int montoDesgasteHerramientas3 = Integer.parseInt(this.jTextField_desgasteHerramientasM3.getText());
        int montoViaticos3 = Integer.parseInt(this.jTextField_viaticosVariablesM3.getText());
        int montoComisiones3 = Integer.parseInt(this.jTextField_comisionesVariableM3.getText());
        int montoSemanaCorrida3 = Integer.parseInt(this.jTextField_semanaCorridaVariableM3.getText());
        DatosEntradaMes mesTres = new DatosEntradaMes(montoSueldoFijo3, montoGratificacion3, montoColacion3, montoMovilizacion3, montoBonoImponible3, montoChequeRestaurant3, montoDesgasteHerramientas3, montoViaticos3, montoComisiones3, montoSemanaCorrida3);
        

        FormularioFiniquito formularioFiniquitoSueldoVariable = 
                new FormularioFiniquito(fechaIngresoFijo, fechaEgresoFijo, diasTomadosVacaciones, artCausalDespido, mesUno, mesDos, mesTres, false);
        
        // mandar a llamar todos los métodos que tienen que calcular algo para guardar en el informe
        // guardar el retorno de cada método en una variable
        FormularioFiniquitoController formularioFiniquitoController = new FormularioFiniquitoController();
        
        FiniquitoCalcController finiquitoCalcController = new FiniquitoCalcController();
        
        int salarioIndemnizacion = formularioFiniquitoController.calcSalarioIndemnizacion(formularioFiniquitoSueldoVariable);
        int salarioVacaciones = formularioFiniquitoController.calcSalarioVacaciones(formularioFiniquitoSueldoVariable);
        double feriadoLegal = formularioFiniquitoController.calcFeriadoLegal(formularioFiniquitoSueldoVariable);
        int indemnizacionAniosServicio = formularioFiniquitoController.calcIndemnizacionAniosServicio(formularioFiniquitoSueldoVariable);
        int indemnizacionVacaciones = formularioFiniquitoController.calcIndemnizacionVacaciones(formularioFiniquitoSueldoVariable);
        LocalDate fechaPagoFiniquito = formularioFiniquitoController.calcFechaPagoFiniquito(formularioFiniquitoSueldoVariable);
        int totalIndemnizacion = formularioFiniquitoController.calcTotalIndemnizacion(formularioFiniquitoSueldoVariable);
        
        
        // instanciar Finiquito(informe)
        Finiquito nuevoFiniquito = new Finiquito();
        nuevoFiniquito.setFechaInicioTrabajo(fechaIngresoFijo);
        nuevoFiniquito.setFechaFinTrabajo(fechaEgresoFijo);
        
        String diasTrabajados = finiquitoCalcController.tiempoTrabajado(nuevoFiniquito);
        nuevoFiniquito.setMesesTrabajadosTotal(diasTrabajados);
        
        nuevoFiniquito.setSalarioIndemnizacion(salarioIndemnizacion);
        nuevoFiniquito.setSalarioVacaciones(salarioVacaciones);
        nuevoFiniquito.setFeriadoLegalHabil(feriadoLegal);
        nuevoFiniquito.setIndeminizacionAniosServicio(indemnizacionAniosServicio);
        nuevoFiniquito.setIndemnizacionVacaciones(indemnizacionVacaciones);
        nuevoFiniquito.setFechaPagoFiniquito(fechaPagoFiniquito);
        nuevoFiniquito.setTotalIndemnizacion(totalIndemnizacion);
        if(sesionUsuario.isSesionValida()){
            nuevoFiniquito.setIdUsuario(sesionUsuario.getUsuarioLogueado().getIdUsuario());
        }
        
        FormInformeFiniquito formInformeFinal = new FormInformeFiniquito(nuevoFiniquito, sesionUsuario);
        formInformeFinal.setVisible(true);
        formInformeFinal.setAlwaysOnTop(true);
        dispose();

    }
//GEN-LAST:event_jButton_calcularFiniquitoSalarioFijo1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FormPanelCentral formPanelCentral = new FormPanelCentral();
        formPanelCentral.setVisible(true);
        formPanelCentral.setAlwaysOnTop(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FormFormularioSueldoFijo formFormularioSueldoFijo = new FormFormularioSueldoFijo();
        formFormularioSueldoFijo.setVisible(true);
        formFormularioSueldoFijo.setAlwaysOnTop(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_salirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu_salirActionPerformed

    private void jMenu_salirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu_salirKeyPressed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jMenu_salirKeyPressed

    private void jMenu_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu_salirMouseClicked

    private void jMenu_salirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_salirMouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu_salirMouseReleased

    private void jTextField_semanaCorridaVariableM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_semanaCorridaVariableM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_semanaCorridaVariableM1ActionPerformed

    private void jTextField_comisionesVariableM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_comisionesVariableM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_comisionesVariableM1ActionPerformed

    private void jTextField_sueldoBaseVariableM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sueldoBaseVariableM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sueldoBaseVariableM1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPanelCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPanelCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPanelCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPanelCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFormularioSueldoFijo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePicker_fechaEgresoFijo;
    private com.github.lgooddatepicker.components.DatePicker datePicker_fechaIngresoFijo;
    private javax.swing.JButton jButton_calcularFiniquitoSalarioFijo1;
    private javax.swing.JButton jButton_limpiarCamposFiniquitoFijo;
    private javax.swing.JCheckBox jCheckBox_zonaExtremaFijo;
    private javax.swing.JComboBox<String> jComboBox_causalesLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMenu_salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_bonoImponibleVariableM1;
    private javax.swing.JTextField jTextField_bonoImponibleVariableM2;
    private javax.swing.JTextField jTextField_bonoImponibleVariableM3;
    private javax.swing.JTextField jTextField_chequeRestaurantVariableM1;
    private javax.swing.JTextField jTextField_chequeRestaurantVariableM2;
    private javax.swing.JTextField jTextField_chequeRestaurantVariableM3;
    private javax.swing.JTextField jTextField_colacionVariableM1;
    private javax.swing.JTextField jTextField_colacionVariableM2;
    private javax.swing.JTextField jTextField_colacionVariableM3;
    private javax.swing.JTextField jTextField_comisionesVariableM1;
    private javax.swing.JTextField jTextField_comisionesVariableM2;
    private javax.swing.JTextField jTextField_comisionesVariableM3;
    private javax.swing.JTextField jTextField_desgasteHerramientasM1;
    private javax.swing.JTextField jTextField_desgasteHerramientasM2;
    private javax.swing.JTextField jTextField_desgasteHerramientasM3;
    private javax.swing.JTextField jTextField_gratificacionVariableM1;
    private javax.swing.JTextField jTextField_gratificacionVariableM2;
    private javax.swing.JTextField jTextField_gratificacionVariableM3;
    private javax.swing.JTextField jTextField_movilizacionVariableM1;
    private javax.swing.JTextField jTextField_movilizacionVariableM2;
    private javax.swing.JTextField jTextField_movilizacionVariableM3;
    private javax.swing.JTextField jTextField_semanaCorridaVariableM1;
    private javax.swing.JTextField jTextField_semanaCorridaVariableM2;
    private javax.swing.JTextField jTextField_semanaCorridaVariableM3;
    private javax.swing.JTextField jTextField_sueldoBaseVariableM1;
    private javax.swing.JTextField jTextField_sueldoBaseVariableM2;
    private javax.swing.JTextField jTextField_sueldoBaseVariableM3;
    private javax.swing.JTextField jTextField_viaticosVariablesM1;
    private javax.swing.JTextField jTextField_viaticosVariablesM2;
    private javax.swing.JTextField jTextField_viaticosVariablesM3;
    private javax.swing.JTextPane jTextPane_diasVacacionesTomados;
    // End of variables declaration//GEN-END:variables
}
