/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ponyseba.finiquitoscalc.view;

import com.ponyseba.finiquitoscalc.controller.FiniquitoCalcController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Finiquito;
import model.SesionUsuario;

/**
 *
 * @author ponyta
 */
public class FormEliminarFiniquito extends javax.swing.JFrame {
    SesionUsuario sesionUsuario;
    /**
     * Creates new form FormEliminarFiniquito
     */
    public FormEliminarFiniquito() {
        initComponents();
    }
    
    public FormEliminarFiniquito(SesionUsuario sesionUsuario){
        initComponents();
        this.sesionUsuario = sesionUsuario;
        this.jpnl_eliminarFiniquito.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_idFiniquito = new javax.swing.JTextField();
        jbtn_buscarFiniquito = new javax.swing.JButton();
        jpnl_eliminarFiniquito = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_listaFiniquitos = new javax.swing.JTable();
        jbtn_eliminarFiniquito = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ligconsolata", 1, 36)); // NOI18N
        jLabel1.setText("Eliminar finiquito del sistema");

        jLabel2.setFont(new java.awt.Font("Ligconsolata", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese ID de Finiquito para buscar:");

        jtxt_idFiniquito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idFiniquitoActionPerformed(evt);
            }
        });

        jbtn_buscarFiniquito.setText("Buscar finiquito");
        jbtn_buscarFiniquito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarFiniquitoActionPerformed(evt);
            }
        });

        jpnl_eliminarFiniquito.setBackground(new java.awt.Color(255, 255, 255));
        jpnl_eliminarFiniquito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Finiquito a eliminar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ligconsolata", 0, 14))); // NOI18N

        jtbl_listaFiniquitos.setFont(new java.awt.Font("Ligconsolata", 0, 18)); // NOI18N
        jtbl_listaFiniquitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Finiquito", "Nombre trabajador", "Tiempo trabajado", "Feriado legal", "Indem. años servicio", "Indem. vacaciones", "Total"
            }
        ));
        jScrollPane1.setViewportView(jtbl_listaFiniquitos);
        if (jtbl_listaFiniquitos.getColumnModel().getColumnCount() > 0) {
            jtbl_listaFiniquitos.getColumnModel().getColumn(0).setPreferredWidth(15);
        }

        jbtn_eliminarFiniquito.setText("Eliminar finiquito");
        jbtn_eliminarFiniquito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarFiniquitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnl_eliminarFiniquitoLayout = new javax.swing.GroupLayout(jpnl_eliminarFiniquito);
        jpnl_eliminarFiniquito.setLayout(jpnl_eliminarFiniquitoLayout);
        jpnl_eliminarFiniquitoLayout.setHorizontalGroup(
            jpnl_eliminarFiniquitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jpnl_eliminarFiniquitoLayout.createSequentialGroup()
                .addGap(433, 433, 433)
                .addComponent(jbtn_eliminarFiniquito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnl_eliminarFiniquitoLayout.setVerticalGroup(
            jpnl_eliminarFiniquitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_eliminarFiniquitoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_eliminarFiniquito, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Volver al Menú Principal");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 300, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jbtn_buscarFiniquito))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_idFiniquito, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jpnl_eliminarFiniquito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_idFiniquito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jbtn_buscarFiniquito, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnl_eliminarFiniquito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_idFiniquitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idFiniquitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idFiniquitoActionPerformed

    private void jbtn_buscarFiniquitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarFiniquitoActionPerformed
        FiniquitoCalcController finiquitoCalcController = new FiniquitoCalcController();
        
        int idFiniquito = Integer.parseInt(this.jtxt_idFiniquito.getText());
        
        Finiquito finiquito = finiquitoCalcController.buscarFiniquitoPorIdFiniquito(sesionUsuario, idFiniquito);
        
        String nombreTrabajador = finiquito.getNombreTrabajador();
        String mesesTrabajadosTotal = finiquito.getMesesTrabajadosTotal();
        double feriadoLegalHabil = finiquito.getFeriadoLegalHabil();
        int indemnizacionAniosServicio = finiquito.getIndeminizacionAniosServicio();
        int indemnizacionVacaciones = finiquito.getIndemnizacionVacaciones();
        int totalIndemnizacion = finiquito.getTotalIndemnizacion();
        
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_listaFiniquitos.getModel();
        
        modelo.setRowCount(0);
        
        modelo.addRow(new Object[]{idFiniquito, nombreTrabajador, mesesTrabajadosTotal, feriadoLegalHabil, indemnizacionAniosServicio, indemnizacionVacaciones, totalIndemnizacion});

        this.jpnl_eliminarFiniquito.setVisible(true);
        
        
        
    }//GEN-LAST:event_jbtn_buscarFiniquitoActionPerformed

    private void jbtn_eliminarFiniquitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarFiniquitoActionPerformed
        
        int resp = JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar este finiquito del sistema?", "Eliminar finiquito", JOptionPane.YES_NO_OPTION);
        
        if(resp==JOptionPane.YES_OPTION){
            FiniquitoCalcController finiquitoCalcController = new FiniquitoCalcController();
            int idFiniquito = Integer.parseInt(this.jtxt_idFiniquito.getText());
            
            boolean res = finiquitoCalcController.borrarFiniquitoPorIdFiniquito(idFiniquito);
            if(res){
                JOptionPane.showMessageDialog(rootPane, "Finiquito eliminado exitosamente!", "Finiquito eliminado", 1);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error!", "Error", 1);
            }
            
        }
    }//GEN-LAST:event_jbtn_eliminarFiniquitoActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        FormPanelCentral formPanelCentral = new FormPanelCentral(sesionUsuario);
        formPanelCentral.setVisible(true);
        formPanelCentral.setAlwaysOnTop(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEliminarFiniquito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEliminarFiniquito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEliminarFiniquito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEliminarFiniquito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEliminarFiniquito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_buscarFiniquito;
    private javax.swing.JButton jbtn_eliminarFiniquito;
    private javax.swing.JPanel jpnl_eliminarFiniquito;
    private javax.swing.JTable jtbl_listaFiniquitos;
    private javax.swing.JTextField jtxt_idFiniquito;
    // End of variables declaration//GEN-END:variables
}
